### ISSUE TITLE
Личная страница. Блок: Часто задаваемые вопросы 

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#11]
Основная задача - #7 

Блок должен содержать:
Могу ли я стать волонтёром и как?
Почему в анкете волонтёра запрашивается личные данные?
Могу ли я заниматься волонтерской деятельностью если мне нет 18?
Каковы направления работы волонтёров? Чем именно занимаются волонтёры?
Волонтёрам платят?
Волонтерство не будет мешать учёбе?
Как получить волонтерскую книжку?
Что получают волонтеры?
Обязательно ли знание иностранных языков, чтобы быть волонтёром?
Обязательно ли принимать участие во всех мероприятиях?
Как нас найти?

**Comment by VinogradovAlexandr781227** [comment]
Задача готова к слиянию, но я вынужден его отложить в связи с техническими проблемами, а именно не стабильной работой интернета уже 2 дня. 
Как только интернет соединение будет восстановлено задача будет успешно клонирована в репозиторий.

**Comment by Proffet78** [comment]
Изменения приняты! Обращаю внимание:
**Блок должен быть залит НЕ ПОЗДНЕЕ 12.06.20201 23:59**
После того как страница будет залита необходимо:
1) Указать подробно что добавлено в блоке
2) добавить комментарий обновления блока и переассанить задачу на меня
После проверки задача будет закрыта - блок будет выполнен!

Сейчас приступай к реализации 2 спринта, подробнее твои задачи описаны в плане 2 спринта - #13 

Удачи!)

**Comment by VinogradovAlexandr781227** [comment]
На рефлексии был вынесен вопрос о перенесении раздела "Часто задаваемые вопросоы (FAQ)" на главную страницу сайта, для удобства пользователя. 

Одобрено Тимлидом: Машариным Валерием

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, задача выполнена! Поздравляю!

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
