### ISSUE TITLE
Личная страница. Блок: Основные ссылки и данные 

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#12]
Основная задача - #7 

Блок должен содержать:
Ссылка на страницу ВКонтакте 
Ссылка на инстаграм
Ссылка на почтовый ящик организации
Ссылка на страницу в Фейсбук

**Comment by VinogradovAlexandr781227** [comment]
Задача готова к слиянию, но я вынужден его отложить в связи с техническими проблемами, а именно не стабильной работой интернета уже 2 дня. 
Как только интернет соединение будет восстановлено задача будет успешно клонирована в репозиторий.

**Comment by Proffet78** [comment]
Изменения приняты! Обращаю внимание:
**Блок должен быть залит НЕ ПОЗДНЕЕ 12.06.20201 23:59**
После того как страница будет залита необходимо:
1) Создать pull reqests
2) Указать подробно что добавлено в блоке
3) добавить комментарий обновления блока и переассанить задачу на меня
После проверки задача будет закрыта - блок будет выполнен!

Сейчас приступай к реализации 2 спринта, подробнее твои задачи описаны в плане 2 спринта - #13 

Удачи!)

**Comment by VinogradovAlexandr781227** [comment]
Комит: 'SPRINT1 LK_commit-3' загружен.

Ожидаю проверки выполнения задачи.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, Коммит одобрен с незначительными комментариями, которые будут указаны в основной задаче ЛК спринта1 - задача выполнена! Поздравляю!

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
