### ISSUE TITLE
План SPRINT 2

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#13]
План КР - #3
СРОК РЕАЛИЗАЦИИ: варьировочный до 13 июня + возможно продление, но не дольше чем до 15.06

**План спринта:**
1) Мануальное тестирование основной страницы - ВИНОГРАДОВ -
2) _Мануальное тестирование ЛК - МАШАРИН - #17 - В ПРОЦЕССЕ_
3) Сборка проекта
4) Отчет по спринту
5) План на 3 спринт

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , Саш, тебе необходимо, во время реализации этого спринта поднять задачу Создание формы Регистрации/Авторизации ЛК

**Comment by Proffet78** [comment]
Соответственно реализовать эту форму, после успешного тестирования мной ЛК, поднимешь задачу, где свяжешь форму и саму страницу!

На данный момент это твоя задача на 2 спринт!
Как зальем ЛК и ОС - появится еще одна задача мануального тестирования

**Comment by VinogradovAlexandr781227** [comment]
Прошу выдать задание на второй спринт

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, твоё первое задание на 2 спринт - issues - #15

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, @Proffet78  НЕОБХОДИМО ПОДНЯТЬ ФОРМЫ МАНУАЛЬНОГО ТЕСТИРОВАНИЯ!!!

**Comment by Proffet78** [comment]
Sprint завершен с опозданием
