### ISSUE TITLE
Диаграмма UML

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#14]
Разработать UML диаграмму для проекта

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by Proffet78** [comment]
@ssas18 , можешь приступать к заданию

**Comment by ssas18** [comment]
Если вопросов по данной uml не будет, то заливаю в репозиторий
![Untitled Document](https://user-images.githubusercontent.com/47377817/87547323-9c2f1b80-c6b3-11ea-9046-05207fb16957.jpg)

**Comment by Proffet78** [comment]
@ssas18 , на данный момент замечаний нет - создавай запрос на слияние

**Comment by YuriSilenok** [comment]
> Если вопросов по данной uml не будет, то заливаю в репозиторий

- Для проверки, в том числе диаграмм которые будут храниться в репозитории предназначены запросы на слияние. Именно там можно увидеть кто проверил, а кто еще нет и многое другое. 
  - 1 Почему **организатор** два раза соединен с **Зарегистрироваться**?
  - 2 Это два соединения с **Посмотреть главную страницу** или линия которая не имеет отношение к этому объекту?
  - 3 Думаю это все же два отдельные линии соединены, но на таких диаграммах используются прямые линии. В чат кинул ссылку на книгу, да бы не публиковать ссылки в публичном месте. 
- Я не вижу здесь отношений между вариантами использования. Пожалуйста, разберитесь с примерами в книге.

![image](https://user-images.githubusercontent.com/14871471/87588064-b684eb80-c6eb-11ea-9745-e928a1546dee.png)

**Comment by Proffet78** [comment]
Задача выполнена
