### ISSUE TITLE
Реализовать регистрацию пользователя на Django

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#15]
Реализовать регистрацию пользователя на Django
======
Story - #35 
Epic - #34 
ERD - #48

**Comment by VinogradovAlexandr781227** [comment]
Приступил к выполнению согласно техническому заданию

**Comment by Proffet78** [comment]
Форму входа(авторизации) сделал на ОС сайта, поэтому необходимо сделать только форму регистрации!

**Comment by Proffet78** [comment]
Из-за перепланировки задачу переносим на 3 спринт

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by JennyShel18** [comment]
Смержено

**Comment by Proffet78** [comment]
Задача одобрена
