### ISSUE TITLE
Реализовать регистрацию события на Django

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#16]
Реализовать регистрацию события на Django
======
Story - #40  
Epic - #39 
ERD - #46

**Comment by Proffet78** [comment]
Из-за перепланировки задачу переносим на 3 спринт

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ответсвенного на эту задачу

**Comment by VinogradovAlexandr781227** [comment]
Начал реализацию задачи

**Comment by VinogradovAlexandr781227** [comment]
Залил пул реквест. Ожидаю проверки задания

**Comment by YuriSilenok** [comment]
> Залил пул реквест. Ожидаю проверки задания

![image](https://user-images.githubusercontent.com/14871471/87217931-25aeb880-c357-11ea-94b7-fefa6e21917b.png)
Где линк на запрос?

**Comment by Proffet78** [comment]
Также нету пулреквеста - где он?

**Comment by YuriSilenok** [comment]
> Также нету пулреквеста - где он?

пулл реквест я называю запросом
![image](https://user-images.githubusercontent.com/14871471/87222241-eeea9980-c37a-11ea-976f-aa1a87e11dd7.png)

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by VinogradovAlexandr781227** [comment]
замержил

**Comment by Proffet78** [comment]
Задача зачтена!
