### ISSUE TITLE
Мануальное тестирование ЛК

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#17]
План спринта - #13

Задача: протестировать форму поднять задачи на баги/изменения/дополнения:
_Задача будет считаться выполненной при исправлении всех багов и недочетов, на каждое исправление необходимо поднимать задачу, название коммита исправления:
SPRINT2_LK_BUG-*, где * - номер бага_

Найденные БАГИ:
1. Изменить цветовую гамму проекта - #19
2. Возможность редактирования  информации - #21
3. Информацию брать из формы регистрации (это дополнение, а не баг) 
4. Кнопка "ОС" - #20
5. Блоки информации - #18
6. Вид ссылок - #22

**Comment by Proffet78** [comment]
Приступил к мануальному тестированию ЛК!

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , на данный момент мануальное тестирование ЛК завершено! Все баги подняты, время на исправление 1,5 дня!

**Comment by Proffet78** [comment]
Продлеваем мануальное тестирование на 3 спринт!

**Comment by VinogradovAlexandr781227** [comment]
Мануальное тестирование выполнено. Задача завершена.

**Comment by VinogradovAlexandr781227** [comment]
Мануальное тестирование выполнено. Задача завершена.
