### ISSUE TITLE
BUG_LK_Блок информации

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#18]
Основная задача bug - #17 
План спринта - #13 

Суть:
Нет все блоков информации в ЛК!

Необходимо:
Добавить блоки согласно выборке ТЗ:
https://docs.google.com/document/d/1EDMUCsDEZ6FAxaGMS4FP9Dlt6or4nkYxGkBaUDeUsX4/edit

**Comment by Proffet78** [comment]
До конца дня баг должен быть исправлен!

**Comment by VinogradovAlexandr781227** [comment]
В связи с моей ошибкой эти изменения были залиты ранее с другим комитом. Ожидаю проверки.

**Comment by Proffet78** [comment]
Зачтено.
