### ISSUE TITLE
BUG_LK_Изменить цветовую гамму проекта

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#19]
Основная задача bug - #17 
План спринта - #13 

Суть:
Неверно выбрана цветовая гамма проекта!

Необходимо:
Сделать цветовую гамму согласно тз, используя цвета (красный, синий, серый, белый). Номера цветовой палитры можно увидеть в ТЗ_Проекта #1

**Comment by VinogradovAlexandr781227** [comment]
Задача выполнена.  'SPRINT2_LK_BUG-2' . Ожидание проверки.

**Comment by Proffet78** [comment]
Нет комита с таким названием!

**Comment by Proffet78** [comment]
Неверная цветовая палитра! 
**Цвета:**
Красный - 8B0000
Синий - 191970
Серый - 2f2f2f
Темный серый - 222222
Белый - ffffff

ИСПОЛЬЗУЕМ только эти цвета! + подбери красивое сочетание!

**Comment by Proffet78** [comment]
До конца дня баг должен быть исправлен!

**Comment by VinogradovAlexandr781227** [comment]
Задача выполнена. Исполнение в 'SPRINT3_LK_BUG_1'. Ожидаю проверки

**Comment by VinogradovAlexandr781227** [comment]
Задача выполнена. Изменения в задаче #43 в коммите 'SPRINT3_LK_BUG_1'. Ожидаю проверки выполнения.

**Comment by VinogradovAlexandr781227** [comment]
Мерж выполнен.

**Comment by Proffet78** [comment]
Зачтено
