### ISSUE TITLE
BUG_LK_Кнопка "ОС"

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#20]
Основная задача bug - #17
План спринта - #13

Суть:
Нет ссылки на страницу ОС

Необходимо:
Вместо кнопки "Ссылка на меня" в шапке страницы, сделать кнопку-ссылку на страницу ОС!

**Comment by VinogradovAlexandr781227** [comment]
Задача выполнена. 'SPRINT2_LK_BUG-3'. Ожидание проверки.

**Comment by Proffet78** [comment]
Задача НЕ ЗАЩИТАНА:
1) исправь ошибку не на ЛАВНУЮ СТРАНИЦУ, а НА ГЛАВНУЮ
2) При нажатие кнопки страница не открывается

**Comment by VinogradovAlexandr781227** [comment]
Валера, добавь связи с общими групповыми стилями.

**Comment by Proffet78** [comment]
Готово! Коммит OTVET_ERROR!

**Comment by VinogradovAlexandr781227** [comment]
Задача выполнена. Исправление в 'SPRINT2_LK_BUG_4'. Ожидаю проверки.

**Comment by Proffet78** [comment]
Баг исправлен. Работа засчитана!
