### ISSUE TITLE
BUG_LK_Возможность редактирования информации

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#21]
Основная задача bug - #17
План спринта - #13

Суть:
Нет возможности редактировать информацию!

Необходимо:
ДЛЯ НАЧАЛА УБЕДИСЬ ЧТО ВЫПОЛНЕНА ЗАДАЧА - #18 
Согласно ТЗ необходимо добавить возможность редактирования каждого ОТДЕЛЬНО блока личной информации!

**Comment by Proffet78** [comment]
До конца дня баг должен быть исправлен!

**Comment by VinogradovAlexandr781227** [comment]
На данный момент нет смысла в реализации данной задачи в связи переносом проекта на Jango. Думаю стоит приостановить действия по данной задаче на неопределенный период (до полного переноска на jango). Ожидаю ответа.

**Comment by Proffet78** [comment]
Так как задача связана с БД напрямую, я согласен с твоим комментарием
