### ISSUE TITLE
BUG_LK_Вид ссылок

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#22]
Основная задача bug - #17
План спринта - #13

Суть:
Некрасивый вид ссылок!

Необходимо:
Сделай вид ссылок красивый и измени название credits!

**Comment by VinogradovAlexandr781227** [comment]
Задача сделана. Исправление в 'SPRINT2_LK_BUG_6'. Ожидаю проверки

**Comment by Proffet78** [comment]
Баг исправлен. Работа засчитана!
