### ISSUE TITLE
Мануальное тестирование ОС

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#23]
План спринта - #13

Задача: протестировать форму поднять задачи на баги/изменения/дополнения:
Задача будет считаться выполненной при исправлении всех багов и недочетов, на каждое исправление необходимо поднимать задачу, название коммита исправления:
SPRINT2_OS_BUG-*, где * - номер бага

Найденные БАГИ:
1. ВолонтИрство - #24 
2. Роли волонтеров - #25 
3. Добавить таблицу событий, а также кнопку ссылку на добавление события - #26 
4. В блоке ЛИЧНЫЙ КАБИНЕТ не видны вводимые символы - #27

**Comment by Proffet78** [comment]
Приступил к исправлению.

**Comment by Proffet78** [comment]
Продлеваем мануальное тестирование на 3 спринт!

**Comment by Proffet78** [comment]
Мануальное тестирование проекта завершено успешно!
