### ISSUE TITLE
BUG_OS_ВолонтИрство

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#24]
Основная задача bug - #23 
План спринта - #13 

Суть:
Лексическая ошибка

Нужно:
На основной странице в шапке проекта исправить надпись Voluneers на 'Volunteers'

**Comment by Proffet78** [comment]
Баг исправлен! Исправления в коммите SPRINT2_OS_BUG-1! 
Ожидаю проверки!

**Comment by VinogradovAlexandr781227** [comment]
Баг исправлен. Работа засчитана!
