### ISSUE TITLE
BUG_OS_Роли волонтеров

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#25]
Основная задача bug - #23 
План спринта - #13 

Суть:
Отстутствующий функционал

НУЖНО:
Блок Роли волонтеров пустует. Добавить требующуюся информацию.

**Comment by Proffet78** [comment]
Залил первые изменения бага (добавил каскадную таблицу). Изменения в SPRINT2_OS_BUG-2.1.
Продолжаю работать над багом.

**Comment by Proffet78** [comment]
До конца дня баг должен быть исправлен!

**Comment by Proffet78** [comment]
Баг не актуален
