### ISSUE TITLE
BUG_OS_Таблица событий

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#26]
Основная задача ошибка - #23  
План спринта - #13 

Суть:
Отсутствие функционала

НУЖНО:
Добавить Таблицы событий

**Comment by Proffet78** [comment]
Залил первые изменения бага. Изменения в SPRINT2_OS_BUG-3.1.
Продолжаю работать над багом.

**Comment by Proffet78** [comment]
Залил изменения бага. Изменения в SPRINT2_OS_BUG-3.2.
Продолжаю работать над багом.

**Comment by Proffet78** [comment]
Баг исправлен! Изменения залиты в SPRINT2_OS_BUG-3.3.
Ожидаю проверки!

**Comment by Proffet78** [comment]
Стоп) Рано!

**Comment by Proffet78** [comment]
Баг исправлен! Изменения залиты в SPRINT2_OS_BUG-3.4.
Ожидаю проверки!

**Comment by VinogradovAlexandr781227** [comment]
Баг исправлен. Работа засчитана!
