### ISSUE TITLE
BUG_OS_Ввод значения в блок Личный кабинет

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#27]
Основная задача bug - #23 
План спринта - #13 

Суть:
Не рабочий функционал

Нужно:
Поля ввода в блоке Личный кабинет не отображают введенные символы

**Comment by Proffet78** [comment]
Баг исправлен! Изменения залиты в SPRINT2_OS_BUG-4. 
Ожидаю проверки!

**Comment by VinogradovAlexandr781227** [comment]
Баг исправлен. Работа засчитана!
