### ISSUE TITLE
Расписать цели и задачи 1 и 2 Sprint

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#3]
План проекта:

Проект подразумевает реализацию ТРЁХ спринтов (недельных).
Ниже расписаны планы, каждого недельного спринта.

SPRINT1 (План спринта - #4) - СРОКИ РЕАЛИЗАЦИИ (варьировочный - относительно до 13.06)
_Спринт на целен на создание репозитория, необходимой документации, оставление всех планов, разработка (модернизация) информации на основной странице сайта и ЛК_

SPRINT2 (План спринта - #13) - СРОКИ РЕАЛИЗАЦИИ (варьировочный - относительно до 20.06)
_Спринт на целен на первоначальное-мануальное тестирование готовых страниц и разработка НОВЫХ ФОРМ (регистрации события, входа/выхода в ЛК). Также спринт на целен на полное-мануальное тестирование готовых страниц, сборка проекта и подготовка материала, создание диаграмм Use-case_

**Comment by Proffet78** [comment]
Спринт 1 завершен, но из-за сильной загруженности не вовремя! Огромный минус, учтем на будущее!

**Comment by Proffet78** [comment]
В связи с решением хранения всей документации ВНЕ репозитория, поэтому _подробны план_ по проекту перенесли на Гугл диск, в таблицу План:

https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB

**Comment by YuriSilenok** [comment]
Пожалуйста, измените заголовок на более детальный

**Comment by YuriSilenok** [comment]
Пожалуйста, измените заголовок на более детальный

**Comment by YuriSilenok** [comment]
Пожалуйста, измените заголовок на более детальный

**Comment by Proffet78** [comment]
Задача неактуальна
