### ISSUE TITLE
План SPRINT 3

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#38]
План КР - #3
СРОК РЕАЛИЗАЦИИ: до 5 июля

**План спринта:**
1) Переехать на Django  - _@JennyShel18_ - #44 
2) Форма Регистрация пользователя  - _@VinogradovAlexandr781227_   -  epic(#34)
3) Форма Регистрация события  - _@proffet78 , @ssas18_  - epic (#39)
4) Отчет по СПРИНТУ 3  - _@proffet78_ 
5) План на СПРИНТ 4 - _@proffet78_

**Comment by YuriSilenok** [comment]
Предполагаю что в плане будут еще линки на задачи которые вы спланировали на спринт. через #
Возможно я не правильно выразился, но управленческую документацию вы ведем в гугл. 
Как минимум эта задача должна иметь ссылку на тот план.
А вообще план в виде задачи создает дополнительную путаницу в задачах. Захламляет доски и статистика получается смазанной

**Comment by YuriSilenok** [comment]
вы можете ставить задачу на планирование, но сам план должен быть в гугл диске, на документ должна вестись ссылка.

**Comment by Proffet78** [comment]
В форме регистрации события и пользователя, распределим задачи на несколько спринтов, в текущем, создать story, ERD-diagram, сценарии автотестов, верстка FE, изучение работы автотестов. 
На 4 спринт оставим разработку автотестов и кодинг.

**Comment by YuriSilenok** [comment]
Если вы что-то перечисляете, делайте это списком:
- раз 
- два
- три

**Comment by Proffet78** [comment]
Итог спринта:

Выполнили:
1) Исправили Баги на старом проекте (НЕ на Django)
2) Разработали Story для событий и пользователя
3) Перевели на Джанго ОС ( #49 )
4) Спроектировали ERD для пользователя и событий, а также разработали структуру БД для событий( #48 #46 #52 )
5) Разработали сценарии для автотестов для регистрации пользователя и события ( #45 #47)

Оценка работы команды:
В целом спринт выполнен полностью за исключением некоторых моментов, с учетом доработки можно оценить работы у в целом на 4, подробную шкалу оценок можно посмотреть во вкладке ХОД таблица ПЛАН
