### ISSUE TITLE
[Epic] Регистрация события

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#39]
Задачи относящиеся к этому эпику должны иметь ссылка на эту задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче
