### ISSUE TITLE
План SPRINT1

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#4]
План КР - #3 
_СРОК РЕАЛИЗАЦИИ: варьировочный до 1 июня + возможно продление_

**План спринта:**

1) **Подготовка начального проекта и всей документации - МАШАРИН, ВИНОГРАДОВ - #5 - ЗАВЕРШЕНО**
2) МОДЕРНИЗАЦИЯ начальной страницы - МАШАРИН -  #6 
3) **МОДЕРНИЗАЦИЯ ЛК ВОЛОНТЁРА - ВИНОГРАДОВ -  #7 - ЗАВЕРШЕНО**

**Comment by Proffet78** [comment]
Продлим сроки спринта до 10.06.2020 из-за технических неполадок, из-за того, что живем в общаге, не было возможности продуктивно работать, так как не работал интернет

**Comment by Proffet78** [comment]
Параллельно начинаем реализацию 2 спринта

**Comment by VinogradovAlexandr781227** [comment]
Описал проблему переноса дедлайна в задачах #9, #10, #11, #12

**Comment by VinogradovAlexandr781227** [comment]
Все задачи по плану выполнены. 

Ожидаю проверки задач и замечаний

**Comment by Proffet78** [comment]
С учетом некоторых трудностей sprint 1 завершен, к сожалению из-за сильно загруженности, не вовремя - это минус

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
