### ISSUE TITLE
[CR] Регистрация события. Капча 

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#42]
Мне как пользователю для завершения регистрации событи необходимо пройти этап верификации при помощи капчи

=======
Epic #39 
Stroy #40

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
