### ISSUE TITLE
Перевести проект на django

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#44]
Перевести проект на джанго, ВОЗМОЖНО ТОЛЬКО ПОСЛЕ ЗАКРЫТИЯ ЗАДАЧИ #19

**Comment by Proffet78** [comment]
@JennyShel18 , Женя твоя задача на спринт перевести проект на DJANGO

**Comment by JennyShel18** [comment]
В данном спринте думаю, что не успею реализовать перевод всего проекта на DJANGO. Предлагаю из этой задачи выделить две подзадачи: это перевод страницы ОС на django и перевод страницы ЛК на DJANGO

**Comment by Proffet78** [comment]
Думаю, что это уместно, так легче отследить выполняемому, однако постарайся успеть перевести до конца спринта, дальше будем судить по факту, не забывай отмечать в журнале)
Поднимай две подзадачи, не забудь сослаться на эту , как на основную, в остально приступай к выполнению!)

**Comment by JennyShel18** [comment]
Спасибо, приступаю.

**Comment by Proffet78** [comment]
Проект переведен на django
