### ISSUE TITLE
Написать сценарии автотестов для Событий

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#45]
Разработать сценарии для автотестов.

Необходимо на [диске](https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing) создать таблицу сценариев и заполнить ее.

Срок выполнения до 23:59 03.07.2020

======
Epic - #39
Story - #40

**Comment by ssas18** [comment]
Сделал таблицу сценариев для автотестов (https://docs.google.com/spreadsheets/d/1aVgza46Gs03fha8xXcO086s3ErTJY7gA69Ppoh8FYHs/edit?usp=sharing)
На истину в первой инстанции не претендую, слушаю ваши замечания.

**Comment by Proffet78** [comment]
@ssas18 , Саш, посмотрел сценарии в целом **замечание одинаковое:**

> _Сценарии подогнаны под прогу, а не под сайт ( у нас НЕТ объекта класса, НО есть объект БД (т.е. изначально проверяется есть ли таблицы, а затем добавляется СТРОКИ в таблицы;  нету метода insert и т.д.)_
*В некоторых строчках оставил комментарий, далее так как пошли однотипные вариации, дублировать не стал

Перепиши сценарии под сайт, а точнее по Django, посмотри может в интернете есть комментарии, как сделать автотесты и сценарии к ним на Django!

**Исправляй до 05.07.2020 18:00 - > далее в понедельник уточним у Юрия Викторовича, что и как, после чего на следующем спринте дам отдельное время для исправления сценариев.**

**Comment by ssas18** [comment]
Исправил некоторые недочеты

**Comment by Proffet78** [comment]
@ssas18 , Саша, в целом сценарии принял, по некоторым моментам посмотрим на замечание Юрия Викторовича и в следующем спринте исправим недочеты, если они будут.

**Comment by ssas18** [comment]
Исправить сценарии автотестов Событий

**Comment by ssas18** [comment]
[исправлено](https://docs.google.com/spreadsheets/d/1aVgza46Gs03fha8xXcO086s3ErTJY7gA69Ppoh8FYHs/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by Proffet78** [comment]
Сценарии одобрены
