### ISSUE TITLE
Разработать Erd для событий

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#46]
====
Epic #39 
Story #40

**Comment by Proffet78** [comment]
Разработал ER Diagram для Events:

https://drive.google.com/file/d/1LjpH7twK-YInOIKGRfFHYFGNur_pxWTM/view?usp=sharing

**Comment by ssas18** [comment]
@proffet78 , ERD одобрена, при условии если будут изменения от Юрия Викторовича, необходимо будет переоткрыть и исправить

**Comment by Proffet78** [comment]
Исправить ERD согласно замечаниям.

**Comment by Proffet78** [comment]
Исправил ERD для событий:
https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing

**Comment by ssas18** [comment]
ERD событий принята
