### ISSUE TITLE
Написать сценарии для автотестов регистрации пользователя

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#47]
Разработать сценарии для автотестов.

Необходимо на диске в таблице сценариев и заполнить ее.(https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing)

Срок выполнения до 23:59 04.07.2020

======
Epic - #34 
Story - #35

**Comment by VinogradovAlexandr781227** [comment]
Сделал таблицу сценариев для автотестов :(https://docs.google.com/spreadsheets/d/1aVgza46Gs03fha8xXcO086s3ErTJY7gA69Ppoh8FYHs/edit?usp=sharing)

**Comment by ssas18** [comment]
@VinogradovAlexandr781227 Саша, в целом сценарии принял, по некоторым моментам посмотрим на замечание Юрия Викторовича и в следующем спринте исправим недочеты, если они будут.

**Comment by Proffet78** [comment]
Исправить сценарии автотесты для регистрации пользователя согласно замечаниям

**Comment by VinogradovAlexandr781227** [comment]
Автотесты исправлены. Жду проверки

**Comment by ssas18** [comment]
Нет сценариев автотестов с не нулевым начальным условием

**Comment by Proffet78** [comment]
Не согласен с замечанием на момент открытия формы, поля должны быть пустыми

**Comment by VinogradovAlexandr781227** [comment]
Для данных сценариев нецелесообразно делать проверку на не нулевые значения. Изначально, когда пользователь загружает форму значения нулевые, далее все процессы происходят по ввзову регистрации

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
Задача выполнена

**Comment by YuriSilenok** [comment]
> Исправить автотесты для регистрации пользователя согласно замечаниям

Задача вроде на разработку сценариев тестирования, причём тут автотесты?

**Comment by Proffet78** [comment]
@YuriSilenok  , да я ошибся при формулировке

На данный момент задача выполнена
