### ISSUE TITLE
Разработать Erd для регистрации пользователя

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#48]
====
Epic #35 
Story #34

**Comment by VinogradovAlexandr781227** [comment]
Разработал ER Diagram для Registration:
https://drive.google.com/file/d/1Fqh4nkVc6sC46Fes0ecfbXIDK6qwmu9Y/view?usp=sharing

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , Саш, привет посмотрел диаграмму, есть несколько замечаний:

> Считаю не очень корректно держать всю информацию ЛК в одной таблице, однако данная часть схемы не относится к заданию, erd для контактной информации ЛК будем разрабатывать позднее

**Из основных замечаний:**

> Не очень понимаю смысла в поле КАПЧА (по идее я бы создал отдельную таблицу, либо по изучал как в Django хранится инфа о капче
**ЕСТЬ ИДЕЯ использовать google-капчу**

> Как идет связь между Регистрацией и Пользователем? По email? 

> В таблице пользователей я бы разделил поле ФИО, на три под поля Фамилия, Имя, Отчество соответственно

**Comment by VinogradovAlexandr781227** [comment]
Всё исправил. Изменения залил на google disc:
https://drive.google.com/file/d/1jR6Y-xyZlmOdZgz1XUvtcLFMGcHGNml-/view?usp=sharing

**Comment by Proffet78** [comment]
Одобрено, до временных замечаний

**Comment by Proffet78** [comment]
Исправить ERD согласно замечаниям

**Comment by ssas18** [comment]
Разработал новую ERD регистрации
https://drive.google.com/drive/folders/1z34KxfFi4ZmRceOzr_ME3ilU5hCta_nT?usp=sharing

**Comment by Proffet78** [comment]
Итак, я проверил, мои замечания:
1) Я бы убрал схему ЛК, так как ERD для ЛК уже написана
2) Связал бы Блог регистрации и блок Личной информации из erd по ЛК

В остальном согласен)

**Comment by ssas18** [comment]
Исправлено

**Comment by Proffet78** [comment]
Засчитано!
