### ISSUE TITLE
Перевести страницу ОС на DJANGO

### ISSUE THREAD

**Issue by JennyShel18** [Proffet78/KR_TRPO_Modern#49]
Является подзадачей основной задачи https://github.com/Proffet78/KR_TRPO_Modern/issues/44

**Comment by JennyShel18** [comment]
1. Все разделы главной страницы перенесены на движок успешно
2. Стили и скрипты подключены, не подключен скрипт validate.js, потому что его не было в папке OS и LK
3. Проблема в кнопке меню, по каким то причинам три полоски в контейнере кнопки сдвинулись немного вверх, решением является в стили добавить padding:12px
4.Эту страницу успею доделать до конца спринта 3, следующую страницу буду делать уже в четвертом спринте, если это возможно

**Comment by Proffet78** [comment]
@JennyShel18 , Жень, создай pull requests с ссылкой на задачу, а не заливай в эту ветку. Проверяющим ставишь меня и ещё кого-нибудь, заливать все будешь в один pull requests

**Comment by JennyShel18** [comment]
Смержено

**Comment by Proffet78** [comment]
Зачтено
