### ISSUE TITLE
Подготовка начального проекта и всей документации

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#5]
План SPRINT1 - #4 
Необходимо загрузить проект, разработать план КР, всех спринтов и необходимой ин-ции.

**Comment by Proffet78** [comment]
Загружена ТЕХНИЧЕСКИЕ ЗАДАНИЯ:
1) самого курсового проекта
2) по реализации сайта

**Comment by Proffet78** [comment]
Создан ПЛАН КР - #3

**Comment by Proffet78** [comment]
Создан план SPRINT1 - #4 
Распределены роли на первый спринт

**Comment by VinogradovAlexandr781227** [comment]
Планы и документацию разработали совместно с Машариным Валерием, для выполнения данного пункта остается только загрузить начальную работу. @Proffet78 сделай это пожалуйста!

**Comment by Proffet78** [comment]
Проект загружен!

**Comment by Proffet78** [comment]
ЗАДАНИЕ ВЫПОЛНЕНО!

**Comment by Proffet78** [comment]
Необходимо более конкретно переформулировать ТЗ, документацию прикрепить в соответствующую задачу (#1 )

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , Саш, эта задача будет лежать на тебе! Срок реализации - до 12:00 06.05.2020

**Comment by VinogradovAlexandr781227** [comment]
Из-за работы смогу отредактировать ближе к вечеру, можно отсрочить до 18?

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , Саша, что с техническим заданием?

**Comment by VinogradovAlexandr781227** [comment]
Повторно высылаю ТЗ:
https://docs.google.com/document/d/1IuSjDg58B7wMf0wuuzwPIq1m9LCKXoc0yMlvNeZdo8Q/edit?usp=sharing

**Comment by Proffet78** [comment]
ТЗ принято!

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
