### ISSUE TITLE
Перевести страницу ЛК на DJANGO

### ISSUE THREAD

**Issue by JennyShel18** [Proffet78/KR_TRPO_Modern#50]
Является подзадачей основной задачи https://github.com/Proffet78/KR_TRPO_Modern/issues/44

**Comment by Proffet78** [comment]
@JennyShel18 , срок выполнения до 08.07.2020.
`до 09.07.2020 задача должна быть закрыта`

**Comment by JennyShel18** [comment]
Поняла

**Comment by Proffet78** [comment]
Задачу зачесть не могу, так как залито только в ветку задачи, необходим пул реквест слияния с веткой dev!

**Comment by Proffet78** [comment]
Оставил комментарии к pull requests

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
ЛК замержен
