### ISSUE TITLE
Разработать структуру БД, для хранения и отображения информации о событии на ОС

### ISSUE THREAD

**Issue by ssas18** [Proffet78/KR_TRPO_Modern#52]
Разработать теоретическую структуру БД, для хранения и отображения информации о событии на ОС с помощью сервера, точнее описание содержания полей.

**Comment by ssas18** [comment]
Разработал структуру БД
(https://docs.google.com/spreadsheets/d/10OKlK5QR5-h9wNK75JpkNeDgQoO0H5HsgILfM2eQk9Q/edit?usp=sharing)

**Comment by Proffet78** [comment]
@ssas18 , структура одобрена, до временных изменений
