### ISSUE TITLE
[Story] Личный Кабинет

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#56]
Зайдя на личную страницу во первых я должен иметь возможность вернуться на Основную страницу.

Во вторых я должен увидеть некоторую информацию о пользователе, которую можно редактировать.
  

- Первый блок "Обо мне": я должен иметь возможность редактировать своё краткое описание используя любые символы, буквы и т.д.
-   Второй блок "Личная фотография": я должен иметь возможность добавить и редактировать  фотографию, нажав на кнопку выбрать файл. Должен иметь возможность сохранить её в профиле. 
-   Третий блок "Гражданство": Я должен иметь возможность ввести и редактировать  дату рождения и гражданство по шаблонам, которые указаны.
-   Четвертый блок "Личная информация": Я должен иметь возможность ввести и редактировать Фамилию, Имя, Отчество и пол по указанным шаблонам.
-   Пятый блок "Место рождения": Я должен иметь возможность ввести и редактировать страну, регион и город по указанным шаблонам.
-   Шестой блок "Размер одежды": Я должен иметь возможность ввести и редактировать Размер футболки, брюк и обуви, а так же рост по указанным шаблонам.
-   Седьмой блок "Адрес регистрации": я должен иметь возможность ввести и редактировать Индекс, Страну, Регион, город, улицу, Дом корпус квартиру, по указанным шаблонам.
-   Восьмой блок "Адрес фактического места жительства": Я должен иметь возможность ввести и редактировать Индекс, Страну, Регион, город, улицу, Дом корпус квартиру, по указанным шаблонам.
-   Девятый блок "Контактная информация": Я должен иметь возможность ввести и редактировать мобильный телефон, дополнительный телефон, логин Skype, по указанным шаблонам.
-   Десятый блок "Контактная информация для экстренных случаев": Я должен иметь возможность ввести Имя, Отчество, телефон, по указанным шаблонам.
-   Одиннадцатый блок "Образование и работа": Я должен иметь возможность ввести и редактировать Образование, Страну обучения, Регион обучения, Город обучения, Наименование учебного заведения, Специальность, Год поступления, Работа, Последнее место работы, по указанному шаблону.
-   Двенадцатый блок "Волонтерский опыт": Я должен иметь возможность ввести и редактировать подробное описание и качества волонтера, используя любые символы, буквы и числа.
-   Тринадцатый блок "Предпочтительные функциональные направления": Я должен иметь возможность ввести и редактировать Направления деятельности используя любые символы, буквы и числа.
-   Четырнадцатый блок "Предпочтительные виды спорта": Я должен иметь возможность ввести и редактировать предпочтительные спортивные направления.
-   Пятнадцатый блок "Ссылки": Я должен иметь возможность вставить в поля ввода ссылки на социальные сети.

В каждом блоке я должен иметь возможность сохранить и редактировать информацию отдельно.

- Если я ввёл не правильное значение в поле, то я должен увидеть рядом с ним знак восклицания, указывающий на ошибку. При наведении на него должно показаться сообщение с указанием критериев правильного ввода в данное поле.
- Если я ввёл информацию правильно, то при нажатии на кнопку Сохранить информация должна сохраниться, а страница должна обновиться.

__________________________________________
Epic #60

**Comment by YuriSilenok** [comment]
Пожалуйста, измените заголовок на более детальный

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , в целом да, есть несколько замечаний, исправь их, а потом закрывай задачу и отметь в журнале о выполнении!

Замечания:
`1) Необходимо _создать_ epic (посмотри другие эпики и создай такой же #39 - для проверки epic после создания **заасань** его на меня; `
`2) В описании задачи необходимо _сослаться_ на epic Личного Кабинета;`
`3) Блок 9 исправь ошибку в слове Skype;`
`4) С 12 блока идет не правильная нумерация задач;`

**Comment by VinogradovAlexandr781227** [comment]
Замечания исправил

**Comment by Proffet78** [comment]
Story принято
