### ISSUE TITLE
[Story] Авторизация пользователя

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#57]
Написать story для авторизации пользователя

**Comment by ssas18** [comment]
Я как пользователь должен иметь возможность авторизоваться на главной странице.

Для этого я должен ввести email который уже есть в БД.
Примеры правильных вариантов ввода: valeriymasharin11@gmail.com, alexandr.vinogradov22@mail.ru

Далее я должен ввести пароль.
Пароль который уже есть в БД и соответствует email  .

После ввода обязательных параметров (email и пароль) я должен иметь возможность нажать на кнопку Вход.
При нажатии кнопки Вход у меня появляется капча. После введения капчи проверяется валидность и наличие введения значений пользователем, путем повторного нажатия на кнопку Вход.

Далее должна обновиться основная страница и появиться форма ЛК.
Критерии приемки:
После нажатия на кнопку Вход  должна произойти валидация критериев Авторизации.

Если я ввел (например) не существующий  email , то я должен увидеть сообщение "Проверьте правильность введенных данных, логин или пароль неверный". Рядом с полем (например) email должен появиться значок восклицания. При наведении на него отображается информация о том, что соответствующее поле введено не правильно.
Если я ввел все данные правильно, при нажатии кнопки Вход у меня должна обновиться основная страница и появиться форма ЛК.

========
Epic - #58

**Comment by Proffet78** [comment]
@ssas18 , в целом да, есть несколько замечаний, исправь их, а потом закрывай задачу и отметь в журнале о выполнении!

Замечания:
`1) Необходимо _создать_ epic (посмотри другие эпики и создай такой же #39 - для проверки epic после создания **заасань** его на меня; `
`2) В описании задачи необходимо _сослаться_ на epic Авторизация пользователя;`
`3) _Нет_ кнопки авторизоваться, есть кнопка "Вход";`
`4) В конце _не может_ появится форма ОС, так как он входит в ЛК, должна открыться его личная страница ЛК;`
