### ISSUE TITLE
[Epic] Авторизация пользователя

### ISSUE THREAD

**Issue by ssas18** [Proffet78/KR_TRPO_Modern#58]
Задачи относящиеся к этому эпику должны иметь ссылка на эту задачу:

**Comment by Proffet78** [comment]
@ssas18 , Саш epic должен находиться в backlog и убери релиз, также в описании необходимо написать:
`"Задачи относящиеся к этому эпику должны иметь ссылка на эту задачу"`

**После выполнения изменений закрывай задачу!**
