### ISSUE TITLE
МОДЕРНИЗАЦИЯ начальной страницы

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#6]
План SPRINT1 - #4

В соответствии с ТЗ сайта #1  -  полностью модернизировать основную страницу

**Comment by Proffet78** [comment]
Приступил к выполнению задания!

**Comment by Proffet78** [comment]
До разработал основную страницу

**Comment by Proffet78** [comment]
Завтра загружу

**Comment by Proffet78** [comment]
Закончил, модернизацию начальной страницы, приступаю к спринту 2! Вечером смогу залить изменения! Задачу закрою, как закрою pull quests!

**Comment by Proffet78** [comment]
Изменения в проекте

**Comment by Proffet78** [comment]
Коммит:  SPRINT1 OS_commit-2  загружен
Необходимо доработать роли и события

**Comment by Proffet78** [comment]
Модернизацию считаю успешно выполненной, при условии, что в ходе 3 спринта добавим роли и события и свяжем страницу с формами! Задача засчитана!

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
