### ISSUE TITLE
Разработать Erd для Личного Кабинета

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#61]
=====
Epic - #60
Story - #56

**Comment by Proffet78** [comment]
Создал ERD для ЛК:
https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing

**Comment by Proffet78** [comment]
Жду одобрения

**Comment by ssas18** [comment]
Все вроде бы хорошо, но есть 1 недочет 
![image](https://user-images.githubusercontent.com/47377817/86952054-12cf9480-c15b-11ea-9135-affdbcbc0263.png)

**Comment by Proffet78** [comment]
Исправил

**Comment by ssas18** [comment]
Одобрено
