### ISSUE TITLE
Мануальное тестирование ЛК (Django)

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#63]
Провести мануальное тестирование ЛК (Django), как сущность FE.

**Comment by Proffet78** [comment]
Нем могу провести мануальное тестирование ЛК, пока на будет закрыта задача #50 , которая направлена на перевод Личного Кабинета Волонтера на Django.

**Comment by Proffet78** [comment]
Так как ЛК до сих пор не залит не могу приступить к тестированию. Жду, Евгению.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
ЛК залито, приступаю к тестированию

**Comment by Proffet78** [comment]
Я конечно, могу ошибаться, но @JennyShel18 , ты подключала стили?

![image](https://user-images.githubusercontent.com/47320491/87391338-3491a700-c5b3-11ea-8fa9-395865f18639.png)

**Comment by Proffet78** [comment]
Мне ответят?

**Comment by YuriSilenok** [comment]
Где-то видел задачу, кажется еще не закрытую, когда она будет выполнена, тестирование не должно производится локально.

**Comment by Proffet78** [comment]
На данный момент это тестирование подразумевает качественный перевод FE , так как в дальнейшем ЛК будет настроен, после этого будут написаны тесты и проведено тестирование автотестами!

**Comment by YuriSilenok** [comment]
То есть, сейчас это интуитивное тестирование. Но я не об этом, меня смутило что тест проводился локально и напомнил, что когда будет настроен сервер, тестирование должно проводится на сервере.

**Comment by JennyShel18** [comment]
@Proffet78  Я тебе уже отвечала, что эти файлы находятся в папке static. Для того, чтобы файлы подключались корректно, тебе нужно скачать питон, django, переопределить командой python manage.py collectstatic и запустить сервер. Только при этих условиях всё будет отображаться корректно

**Comment by YuriSilenok** [comment]
> @Proffet78 Я тебе уже отвечала, что эти файлы находятся в папке static. Для того, чтобы файлы подключались корректно, тебе нужно скачать питон, django, переопределить командой python manage.py collectstatic и запустить сервер. Только при этих условиях всё будет отображаться корректно

Кстати, это есть в обучающем видео, которое скидывалось в чат.

**Comment by JennyShel18** [comment]
Именно

**Comment by Proffet78** [comment]
@JennyShel18 , на данный момент замечаний по FE ЛК нету, ОБРАЩАЮ ВНИМАНИЕ, что после реализации связи ЛК с сервером - ЛК должен корректно отображаться БЕЗ каких-либо подключений!
