### ISSUE TITLE
Создать общую ERD для проекта и прописать структуру

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#67]
Свести все ERD в единую, настроить связи и прописать структуру, возможно подправить erd.

Свести согласно следующим story:
#35 #40 #56 #57

**Comment by Proffet78** [comment]
Свел все диаграммы в единую ERD, файл выложен на диске:
https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
Общая ERD на диске, @ssas18  проверь все ли так, если да, закрывай задачу)

**Comment by ssas18** [comment]
По моему мнению данная ERD корректна

**Comment by YuriSilenok** [comment]
Кажется мы договаривались что ерд будет экспортирована в репозиторий?

**Comment by Proffet78** [comment]
Вечером залью в репозиторий!

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
> Вечером залью в репозиторий!

Так что у нас с этой задачей?

**Comment by Proffet78** [comment]
Занимаюсь этой задачей, сейчас залью, вчера интернета не было к сожалению

**Comment by Proffet78** [comment]
@YuriSilenok , есть уточнения по формату? или можно в любом?

**Comment by YuriSilenok** [comment]
> @YuriSilenok , есть уточнения по формату? или можно в любом?

Я называл вам формат на одной из наших встреч. 
![image](https://user-images.githubusercontent.com/14871471/87587644-0adb9b80-c6eb-11ea-98cc-1aa222ed5168.png)

**Comment by Proffet78** [comment]
Задача выполнена
