### ISSUE TITLE
Нарушено правило именования веток

### ISSUE THREAD

**Issue by YuriSilenok** [Proffet78/KR_TRPO_Modern#68]
['task---16'] Приведите имена веток в соответсвие

**Comment by YuriSilenok** [comment]
['task---16'] Приведите имена веток в соответсвие

**Comment by Proffet78** [comment]
Саша Виноградов твоя ветка неправильная - изменяй!

**Comment by YuriSilenok** [comment]
> Саша Виноградов твоя ветка неправильная - изменяй!

еще лучше указывать вот так человека @VinogradovAlexandr781227 
но я не уверен что у вас появилась привычка следить за почтой

**Comment by YuriSilenok** [comment]
['task---16'] Приведите имена веток в соответсвие

**Comment by YuriSilenok** [comment]
['task---16'] Приведите имена веток в соответсвие

**Comment by VinogradovAlexandr781227** [comment]
Изменил название ветки task---16 на task-16. Извиняюсь за ошибку
