### ISSUE TITLE
Мануальное тестирование FE форм и страниц (не связанных с БД)

### ISSUE THREAD

**Issue by JennyShel18** [Proffet78/KR_TRPO_Modern#69]
_Исправить сбои, если они есть
#49_

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , @JennyShel18 
Так у меня есть несколько вопросов:
На что нацелена задача конкретно?
С каким функционалом работает?
И где можно увидеть баги?

*Отмечу, что на ЛК и ОС задачи для поиска багов направленных на FE разработку подняты.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , @JennyShel18, эта задача сейчас неактуальна -> но будет необходима в 5 спринте, на тестирование мануальное форм -> поэтому изменю все и на ответственного перевешу

**Comment by Proffet78** [comment]
ВНИМАНИЕ! Пояснения к задаче!

В связи с некорректной задачей поднятой ранее, немного переформулирую задачу:

ЦЕЛЬ - мануальное тестирование FE форм и страниц (не связанных с БД)

ХОД:
1) @Proffet78 и @ssas18  проводят соответствующее плану тестирование, в результате ОДНИМ сообщением пишут сюда все баги связанные FE;
2) Далее @VinogradovAlexandr781227  и @JennyShel18  при необходимости исправляют их, заливая исправления в УЖЕ СОЗДАННУЮ ВЕТКУ task-69 , после того как ВСЕ изменения будут залиты идет одобрение слияния @Proffet78 и @ssas18 .

СРОКИ РЕАЛИЗАЦИИ:
1) Мануальное тестирование формы регистрации пользователя (@Proffet78 ) и формы регистрации события (@ssas18 ) ДО 14.07.2020 (до 23:59:59)

2) Исправление багов формы регистрации пользователя (@JennyShel18 ) и формы регистрации события (@VinogradovAlexandr781227 ) ДО 15.07.2020 (до 23:59:59)

**Comment by ssas18** [comment]
Замечаний нет, все на своем месте

![Аннотация 2020-07-14 093131](https://user-images.githubusercontent.com/47377817/87445440-bb20a580-c600-11ea-89b3-87296b50ae3e.png)

**Comment by Proffet78** [comment]
К сожалению, дома отключили интернет, завтра смогу только провести тестирование

**Comment by Proffet78** [comment]
Багов при мануальном тестировании не обнаружено

**Comment by Proffet78** [comment]
Задача выполнена!
