### ISSUE TITLE
МОДЕРНИЗАЦИЯ ЛК ВОЛОНТЁРА

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#7]
План SPRINT1 - #4

В соответствии с ТЗ сайта #1 - полностью модернизировать ЛК ВОЛОНТЁРА

**Блоки:**
1) Личная страница пользователя. Блок основной идентификационной информации - #9
2) Личная страница. Блок: волонтерская информация - #10
3) Личная страница. Блок: Часто задаваемые вопросы - #11
4) Личная страница. Блок: Основные ссылки и данные - #12

**Comment by VinogradovAlexandr781227** [comment]
Начал выполнение

**Comment by Proffet78** [comment]
Как успехи?)

**Comment by Proffet78** [comment]
Саш, как успехи с ЛК?

**Comment by Proffet78** [comment]
ЗАДАЧА БУДЕТ ЗАКРЫТА ПОСЛЕ УСПЕШНОГО ЗАВЕРШЕНИЯ ВСЕХ БЛОКОВ!

**Comment by VinogradovAlexandr781227** [comment]
Все задачи по спринту выполнены.

Ожидаю проверки выполнения и замечаний по ходу работы.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, 
В целом задачу одобряю, в дальнейшем в ходе 3 спринта будет необходимость:
1) Добавление стандартизированного дизайна страниц
2) Возможности редактировать информацию на странице
3) Связь с БД, в том числе с формами авторизации, реализуемыми во 2 спринте!

Молодец! Задача выполнена! Приступай к реализации 2 спринта! Удачи!

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
