### ISSUE TITLE
Разработать сервер для проекта

### ISSUE THREAD

**Issue by JennyShel18** [Proffet78/KR_TRPO_Modern#70]
#67

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by Proffet78** [comment]
@JennyShel18 , в описании необходимо сослать на задачу с общей ERD, сделайте это как можно скорее!

**Comment by YuriSilenok** [comment]
Заголовок странный, я не ронимаю какой объем работы должен быть выполнен.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18 Объясняю, что вы должны сделать в этой задаче:

ДО КОНЦА 13.07.2020 до 23:59:59

В этой задаче должен появиться отчет, о том, что вы:
1) изучили как связать Django с сервером (НЕ ЛОКАЛЬНЫМ)
2) настроили сервер (подключили все службы)
3) Создали БД с необходимыми таблицами

**Comment by JennyShel18** [comment]
Отчет по выполнению задачи
https://drive.google.com/file/d/1eApH1u5IPosPK8GlSENbJK0yokwWyYYD/view?usp=sharing

**Comment by Proffet78** [comment]
@JennyShel18 по какому первому дню? Сегодня срок задания выходит

**Comment by JennyShel18** [comment]
Ошиблась, сейчас исправлю описание

**Comment by Proffet78** [comment]
Таблицы созданы?

**Comment by VinogradovAlexandr781227** [comment]
Да. Таблицы созданы успешно

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18 , в отчете нет инфы про таблицы

**Comment by VinogradovAlexandr781227** [comment]
@Proffet78 В данный момент мы готовим новый отчёт с описанием и скриншотами процесса и таблиц

**Comment by Proffet78** [comment]
Хорошо, для проверки не забудьте заасанить меня

**Comment by VinogradovAlexandr781227** [comment]
https://docs.google.com/document/d/1umxurll2oHSV7tP54XTjwp9I79zr3t6Xyi4tdhLUIpY/edit
Новый отчёт о работе. Сюда будут добавляться все изменения до конца выполнения текущей задачи

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/87589627-2f854280-c6ee-11ea-9ada-f1fb30207972.png)
-  все ваши гугл документы должны создаваться в [рабочей папке](https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing), тогда никому не нужно будет предоставлять доступ. И все остальные документы там так же должны складироваться. Проекты диаграмм в том числе. И продумайте структуру этой папке, пока там свалка.
-  оформляйте ссылки. Бросать URL не культурно. Вы же IT.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , аналогичный комментарий


> ![изображение](https://user-images.githubusercontent.com/14871471/87589627-2f854280-c6ee-11ea-9ada-f1fb30207972.png)
> 
> * все ваши гугл документы должны создаваться в [рабочей папке](https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing), тогда никому не нужно будет предоставлять доступ. И все остальные документы там так же должны складироваться. Проекты диаграмм в том числе. И продумайте структуру этой папке, пока там свалка.
> * оформляйте ссылки. Бросать URL не культурно. Вы же IT.

**Comment by VinogradovAlexandr781227** [comment]
Замечание учёл. Загрузил в [гугл диск](https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB)

**Comment by YuriSilenok** [comment]
> Замечание учёл. Загрузил в гугл диск:
> https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB

Не URL, ССЫЛКУ

**Comment by VinogradovAlexandr781227** [comment]
> > Замечание учёл. Загрузил в гугл диск:
> > https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB
> 
> Не URL, ССЫЛКУ

Апдейтил комент

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
@JennyShel18 , Жень смержи ветку!)

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
