### ISSUE TITLE
Связать форму регистрации события с БД

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#73]
Настроить в форме регистрации события связь с БД

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 Запрос на слияние должен быть поднят до 23:59:59!

**Comment by VinogradovAlexandr781227** [comment]
@Proffet78 Просим продление сроков задач #74 и [#73](https://github.com/Proffet78/KR_TRPO_Modern/issues/73) до завтрашнего вечера в связи с ошибками, возникшими в MySql и Python, которые мы чисто физически сегодня не успеем исправить. В данный момент работаем над этим, но не знаем успеем ли сегодня

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , хорошо, даю вам отсрочку, НО:
1) До конца 16.07 задача должны быть выполнена
2) Задача, которая висит на вас сегодня ТОЖЕ ДОЛЖНЫ БЫТЬ ВЫПОЛНЕНА
3) ОС - страница на которой находятся должна быть уже подключена к серверу, т.е. Я, как пользователь, не должен буду скачать питон и что-то там подключать!

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18 , необходимо связать форму с БД

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18   Как успехи, когда зальете изменения?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
