### ISSUE TITLE
Создать и связать форму регистрации пользователя с БД

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#74]
Настроить связь формы **регистрации** пользователя с БД (только РЕГИСТРАЦИИ).

**Comment by Proffet78** [comment]
@JennyShel18 Запрос на слияние должен быть поднят до 23:59:59!

**Comment by Proffet78** [comment]
@JennyShel18 , я так понимаю, вам тоже нужна отсрочка?

Условия такие же, хорошо, даю вам отсрочку, НО:
1) До конца 16.07 задача должны быть выполнена
2) Задача, которая висит на вас сегодня ТОЖЕ ДОЛЖНЫ БЫТЬ ВЫПОЛНЕНА
3) ОС - страница на которой находятся должна быть уже подключена к серверу, т.е. Я, как пользователь, не должен буду скачать питон и что-то там подключать!

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
Создать форму регистрации пользователя и связать с сервером и главной страницей. 
Срок выполнения до 19.08.2020 до 23:59:59

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18 , необходимо связать форму с БД

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18   Как успехи, когда зальете изменения?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #74 составляет 4 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель
