### ISSUE TITLE
Связать форму авторизации пользователя с БД

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#76]
Настроить в форме авторизации пользователя связь с БД

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18 , необходимо связать форму с БД

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18   Как успехи, когда зальете изменения?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Что с этой задачей, когда планируется её завершение?

**Comment by YuriSilenok** [comment]
Что с этой задачей, когда планируется её завершение?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #76 составляет 4 дней. Активность в ветке task-76 составляет 4 дней. Активность по запросу #86 составляет 3 дней. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
