### ISSUE TITLE
Написать сценарии автотестов для авторизации пользователя

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#77]
Разработать сценарии для автотестов.

Необходимо на [диске](https://drive.google.com/drive/folders/1ZhZMTXkzXQsrGLyEi3NBKh1OWRQOnuYB?usp=sharing) создать таблицу сценариев и заполнить ее.

Срок выполнения до 23:59 16.07.2020

======
Epic - #57
Story - #58

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
Задача принята в работу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@ssas18  Саша Коваленко - твоя задача на спринт

**Comment by ssas18** [comment]
Выполнено!

**Comment by YuriSilenok** [comment]
@ssas18
А с себя не сняли по какой причине? Вы что-то собираетесь делать по задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by ssas18** [comment]
> @ssas18
> А с себя не сняли по какой причине? Вы что-то собираетесь делать по задаче?

запросил проверку у Валеры, а с себя не снимал т.к это способ получать уведомления

**Comment by YuriSilenok** [comment]
> > @ssas18
> > А с себя не сняли по какой причине? Вы что-то собираетесь делать по задаче?
> 
> запросил проверку у Валеры, а с себя не снимал т.к это способ получать уведомления

Вы не правы, вот я не назначен ответственным, но уведомления получаю. Стандартный режим уведомлений таком. Вы получаете уведомления о событиях в задаче или запросе если были хоть раз, упомянуты, заасанены, получали запрос на проверку. В правом нижнем углу задачи или запроса можно увидеть кто подписан на уведомления. Там же есть кнопка подписаться на уведомление если хотите следить за задачей

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #77 составляет 3 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель
