### ISSUE TITLE
Некорректно работает верстка в мобильной версии при изменении масштаба страницы сайта

### ISSUE THREAD

**Issue by JennyShel18** [Proffet78/KR_TRPO_Modern#79]
1.Открыть главную страницу сайта с мобильного устройства http://jennyshel18.pythonanywhere.com/siteDJ/
1.1 Открыть личный кабинет с мобильного устройства http://jennyshel18.pythonanywhere.com/siteDJ/yourCab/
2.Изменить масштаб
Ожидаемый результат:Корректное изменение размера элементов верстки
Фактический результат: Некорректное изменение размеров элементов верстки
![sRFb09WHg18](https://user-images.githubusercontent.com/47378275/89119019-8becae00-d4b3-11ea-9e99-fc69e86d20e7.jpg)
![image](https://user-images.githubusercontent.com/47377817/90976817-fe97f900-e548-11ea-8d9e-38d9e6306a00.png)

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 , задача выдана - необходимо сделать до 18.08.2020 до 23:59:59

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18  Саша, Женя ИСПРАВЬТЕ БАГ!!!!

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #79 составляет 3 дней. Ветка отсутствует. Запрос отсутствует. Нет запросов, которые должен проверить преподаватель

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Устаревшая ветка task-79 будет удалена в ближайшее время

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
