### ISSUE TITLE
Тестирование проекта на сервере

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KR_TRPO_Modern#81]
Мануально протестировать страницы на сервере, расписать недочеты/баги/замечания (под номерами с названием, описанием, скриншотами), расставить приоритеты (при необходимости создай Labels). Учитывай при тестировании возможность просматривать сайт с разных видов устройств (компьютер, телефон)

**Comment by ssas18** [comment]
Каких либо критических багов мною не было выявлено, но есть несколько замечаний:
плохая верстка для моб. устроиств(но этот баг уже поднят #79) 
![image](https://user-images.githubusercontent.com/47377817/90379641-a44bf380-e083-11ea-9a65-b6a395ed745e.png)
![image](https://user-images.githubusercontent.com/47377817/90379669-b0d04c00-e083-11ea-9db7-495915b5478a.png)
A так же не работают кнопки перехода на другие страницы, некоторые просто перекидывают на шапку сайта, некоторые на необработанное исключение.
форма регистрации вылезает в очень странном месте 
![image](https://user-images.githubusercontent.com/47377817/90379945-1ae8f100-e084-11ea-8d00-5b0c526eb1e9.png)

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by Proffet78** [comment]
@ssas18 , подними по каждому недочету задачу, опиши ее, расставь приоритеты и поставь ответственного (либо Сашу Виноградова, либо Женю)
Здесь сделай список поднятых недочетов с ссылками
После этого данный этап тестирования будет завершен - задача будет считаться выполненной

**Comment by Proffet78** [comment]
А также проверь работоспособность всех ссылок, считаю это тоже багом)

**Comment by Proffet78** [comment]
При необходимости отредактируй баг #79

**Comment by ssas18** [comment]
Разделил баги на 2 группы и описал их в #79 и #82

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
Зачтено, 79 и 82 закрываем после выполнения!
