### ISSUE TITLE
Некорректно работают ссылки в проекте 

### ISSUE THREAD

**Issue by ssas18** [Proffet78/KR_TRPO_Modern#82]
Главная страница - http://jennyshel18.pythonanywhere.com/siteDJ/
1 Нажатие на кнопку "подать заявку"
![image](https://user-images.githubusercontent.com/47377817/90976860-664e4400-e549-11ea-9304-e4a007d5b967.png)
Ожидаемый результат - Уведомление о принятой заявке
Фактический результат - Происходит проброс на самый верх данной страницы
2 Нажатие на кнопку "Вход"
![image](https://user-images.githubusercontent.com/47377817/90976890-b927fb80-e549-11ea-9d0a-dbec5fca7b08.png)
Ожидаемый результат - Происходит вход в ЛК
Фактический результат - Необработанное исключение, а точнее ссылка на несуществующую страницу
3 Нажатие на кнопку "Зарегистрироваться"
![image](https://user-images.githubusercontent.com/47377817/90976916-f4c2c580-e549-11ea-8b1e-222e3935d022.png)
Ожидаемый результат - Форма регистрации открывается ровно по середине экрана
Фактический результат - Форма регистрации открывается справа
4 Нажатие на кнопку "Зарегистрировать событие"
![image](https://user-images.githubusercontent.com/47377817/90976961-4ff4b800-e54a-11ea-8441-48141155fa2a.png)
Ожидаемый результат - Происходит вход на форму нового события
Фактический результат - Необработанное исключение, а точнее ссылка на несуществующую страницу
5 Нажатие на кнопку "volonteers"
![image](https://user-images.githubusercontent.com/47377817/90976976-761a5800-e54a-11ea-9467-96efd14f1d75.png)
Ожидаемый результат - Переход на главную страницу сайта
Фактический результат - Необработанное исключение, а точнее ссылка на несуществующую страницу
6 Нажатие на кнопку "соц. сети"
![image](https://user-images.githubusercontent.com/47377817/90976995-a82bba00-e54a-11ea-898d-480d27342f02.png)
Ожидаемый результат - Переход в соответствующую соц. сеть
Фактический результат - Необработанное исключение, а точнее ссылка на несуществующую страницу
==============================================================
Страница личного кабинета - http://jennyshel18.pythonanywhere.com/siteDJ/yourCab/
7 Нажатие на кнопку "ссылка на главную страницу"
![image](https://user-images.githubusercontent.com/47377817/90977012-c85b7900-e54a-11ea-8875-c84a88592a1a.png)
Ожидаемый результат - Переход на главную страницу сайта
Фактический результат - Необработанное исключение, а точнее ссылка на несуществующую страницу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 @JennyShel18   Как успехи, когда зальете изменения?

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227 Саша, исправь баги!!
Поднимаешь отдельно на каждый выше описанный баг задачу - и исправляешь баг! Не забудь ссылку на эту задачу! Здесь после поднятия отписываешься - что начал работу тогда-то, закончу тогда-то!!!!

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности. Активность по основной задаче #82 составляет 3 дней. Активность по ветке отсутствует. Активность по запросу отсутствует.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
