### ISSUE TITLE
Личная страница пользователя. Блок основной идентификационной информации 

### ISSUE THREAD

**Issue by VinogradovAlexandr781227** [Proffet78/KR_TRPO_Modern#9]
Основная задача - #7 

Личная информация должна содержать:
1)ФИО
2)Дата рождения
3)Электронная почта 
4)Домашний адрес
5)Номер телефона 
6)Место учебы/работы
7)Наличие волонтерской книжки

**Comment by VinogradovAlexandr781227** [comment]
Задача готова к слиянию, но я вынужден его отложить в связи с техническими проблемами, а именно не стабильной работой интернета уже 2 дня. 
Как только интернет соединение будет восстановлено задача будет успешно клонирована в репозиторий.

**Comment by Proffet78** [comment]
Изменения приняты! Обращаю внимание:
**Блок должен быть залит НЕ ПОЗДНЕЕ 12.06.20201 23:59**
После того как страница будет залита необходимо:
1) Указать подробно что добавлено в блоке
2) добавить комментарий обновления блока и переассанить задачу на меня
После проверки задача будет закрыта - блок будет выполнен!

Сейчас приступай к реализации 2 спринта, подробнее твои задачи описаны в плане 2 спринта - #13 

Удачи!)

**Comment by VinogradovAlexandr781227** [comment]
Комит: 'SPRINT1 LK_commit-1' загружен. 

Ожидаю проверки выполнения задачи.

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, Коммит одобрен - задача выполнена! Поздравляю!

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче
